//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_ENTITY_FRAMEWORK.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogException
    {
        public int ExceptionID { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string ExceptionMessage { get; set; }
        public string StackTrace { get; set; }
    }
}
