//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_ASP.NET
{


    public partial class _Default
    {

        /// <summary>
        /// PageNameUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Demo_ASP.NET.PageNameUserControl PageNameUserControl;

        /// <summary>
        /// studentcontrol control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Demo_ASP.NET.StudentUserControl studentcontrol;

        /// <summary>
        /// NoteUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Demo_ASP.NET.NoteUserControl NoteUserControl;
    }
}
