//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagement.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingSpace()
        {
            this.VehicleParkings = new HashSet<VehicleParking>();
        }
    
        public int ParkingSpaceId { get; set; }
        public string ParkingSpaceTitle { get; set; }
        public int ParkingZoneId { get; set; }
    
        public virtual ParkingZone ParkingZone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleParking> VehicleParkings { get; set; }
    }
}
